# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fff95d53a080f9bfe7186fabde7962c63e2790aacf76cbeb5eb06c29293b977fedb9a8eaa86cd041f77914f697760a6625781295b06f5484a2c8461678ae0767

test:
  secret_key_base: 7e9d3114d751de1ba085a000257c49b6720be2458e2c9a9c407a433358cc9c6d5a6e2b3e34012b253cc045e4dedfd7d55ee55137c9bf0b31999e7b5ca0218902

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
